/* 
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SCILL.Api;
using SCILL.Model;
using SCILL.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SCILL.Test
{
    /// <summary>
    ///  Class for testing BattlePass
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BattlePassTests
    {
        // TODO uncomment below to declare an instance variable for BattlePass
        //private BattlePass instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BattlePass
            //instance = new BattlePass();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BattlePass
        /// </summary>
        [Test]
        public void BattlePassInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BattlePass
            //Assert.IsInstanceOfType<BattlePass> (instance, "variable 'instance' is a BattlePass");
        }


        /// <summary>
        /// Test the property 'battle_pass_id'
        /// </summary>
        [Test]
        public void battle_pass_idTest()
        {
            // TODO unit test for the property 'battle_pass_id'
        }
        /// <summary>
        /// Test the property 'package_sku'
        /// </summary>
        [Test]
        public void package_skuTest()
        {
            // TODO unit test for the property 'package_sku'
        }
        /// <summary>
        /// Test the property 'name'
        /// </summary>
        [Test]
        public void nameTest()
        {
            // TODO unit test for the property 'name'
        }
        /// <summary>
        /// Test the property 'description'
        /// </summary>
        [Test]
        public void descriptionTest()
        {
            // TODO unit test for the property 'description'
        }
        /// <summary>
        /// Test the property 'truncated_description'
        /// </summary>
        [Test]
        public void truncated_descriptionTest()
        {
            // TODO unit test for the property 'truncated_description'
        }
        /// <summary>
        /// Test the property 'image'
        /// </summary>
        [Test]
        public void imageTest()
        {
            // TODO unit test for the property 'image'
        }
        /// <summary>
        /// Test the property 'image_desktop'
        /// </summary>
        [Test]
        public void image_desktopTest()
        {
            // TODO unit test for the property 'image_desktop'
        }
        /// <summary>
        /// Test the property 'battle_pass_start_date'
        /// </summary>
        [Test]
        public void battle_pass_start_dateTest()
        {
            // TODO unit test for the property 'battle_pass_start_date'
        }
        /// <summary>
        /// Test the property 'battle_pass_end_date'
        /// </summary>
        [Test]
        public void battle_pass_end_dateTest()
        {
            // TODO unit test for the property 'battle_pass_end_date'
        }
        /// <summary>
        /// Test the property 'read_more_link'
        /// </summary>
        [Test]
        public void read_more_linkTest()
        {
            // TODO unit test for the property 'read_more_link'
        }
        /// <summary>
        /// Test the property 'page_id'
        /// </summary>
        [Test]
        public void page_idTest()
        {
            // TODO unit test for the property 'page_id'
        }
        /// <summary>
        /// Test the property 'battle_pass_completed'
        /// </summary>
        [Test]
        public void battle_pass_completedTest()
        {
            // TODO unit test for the property 'battle_pass_completed'
        }
        /// <summary>
        /// Test the property 'package_value_eur'
        /// </summary>
        [Test]
        public void package_value_eurTest()
        {
            // TODO unit test for the property 'package_value_eur'
        }
        /// <summary>
        /// Test the property 'purchased_at'
        /// </summary>
        [Test]
        public void purchased_atTest()
        {
            // TODO unit test for the property 'purchased_at'
        }
        /// <summary>
        /// Test the property 'can_purchase_with_money'
        /// </summary>
        [Test]
        public void can_purchase_with_moneyTest()
        {
            // TODO unit test for the property 'can_purchase_with_money'
        }
        /// <summary>
        /// Test the property 'can_purchase_with_coins'
        /// </summary>
        [Test]
        public void can_purchase_with_coinsTest()
        {
            // TODO unit test for the property 'can_purchase_with_coins'
        }
        /// <summary>
        /// Test the property 'levels'
        /// </summary>
        [Test]
        public void levelsTest()
        {
            // TODO unit test for the property 'levels'
        }

    }

}
