/* 
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SCILL.Api;
using SCILL.Model;
using SCILL.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SCILL.Test
{
    /// <summary>
    ///  Class for testing BattlePassLevelChallenge
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BattlePassLevelChallengeTests
    {
        // TODO uncomment below to declare an instance variable for BattlePassLevelChallenge
        //private BattlePassLevelChallenge instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BattlePassLevelChallenge
            //instance = new BattlePassLevelChallenge();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BattlePassLevelChallenge
        /// </summary>
        [Test]
        public void BattlePassLevelChallengeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BattlePassLevelChallenge
            //Assert.IsInstanceOfType<BattlePassLevelChallenge> (instance, "variable 'instance' is a BattlePassLevelChallenge");
        }


        /// <summary>
        /// Test the property 'challenge_goal'
        /// </summary>
        [Test]
        public void challenge_goalTest()
        {
            // TODO unit test for the property 'challenge_goal'
        }
        /// <summary>
        /// Test the property 'name'
        /// </summary>
        [Test]
        public void nameTest()
        {
            // TODO unit test for the property 'name'
        }
        /// <summary>
        /// Test the property 'current_challenge_amount'
        /// </summary>
        [Test]
        public void current_challenge_amountTest()
        {
            // TODO unit test for the property 'current_challenge_amount'
        }
        /// <summary>
        /// Test the property 'completed'
        /// </summary>
        [Test]
        public void completedTest()
        {
            // TODO unit test for the property 'completed'
        }
        /// <summary>
        /// Test the property 'active'
        /// </summary>
        [Test]
        public void activeTest()
        {
            // TODO unit test for the property 'active'
        }

    }

}
