/* 
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SCILL.Api;
using SCILL.Model;
using SCILL.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SCILL.Test
{
    /// <summary>
    ///  Class for testing LeaderboardV2MemberTypeRanking
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LeaderboardV2MemberTypeRankingTests
    {
        // TODO uncomment below to declare an instance variable for LeaderboardV2MemberTypeRanking
        //private LeaderboardV2MemberTypeRanking instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LeaderboardV2MemberTypeRanking
            //instance = new LeaderboardV2MemberTypeRanking();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LeaderboardV2MemberTypeRanking
        /// </summary>
        [Test]
        public void LeaderboardV2MemberTypeRankingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LeaderboardV2MemberTypeRanking
            //Assert.IsInstanceOfType<LeaderboardV2MemberTypeRanking> (instance, "variable 'instance' is a LeaderboardV2MemberTypeRanking");
        }


        /// <summary>
        /// Test the property 'count'
        /// </summary>
        [Test]
        public void countTest()
        {
            // TODO unit test for the property 'count'
        }
        /// <summary>
        /// Test the property 'members'
        /// </summary>
        [Test]
        public void membersTest()
        {
            // TODO unit test for the property 'members'
        }

    }

}
