/* 
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SCILL.Api;
using SCILL.Model;
using SCILL.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SCILL.Test
{
    /// <summary>
    ///  Class for testing LeaderboardV2UpdatePayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LeaderboardV2UpdatePayloadTests
    {
        // TODO uncomment below to declare an instance variable for LeaderboardV2UpdatePayload
        //private LeaderboardV2UpdatePayload instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LeaderboardV2UpdatePayload
            //instance = new LeaderboardV2UpdatePayload();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LeaderboardV2UpdatePayload
        /// </summary>
        [Test]
        public void LeaderboardV2UpdatePayloadInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LeaderboardV2UpdatePayload
            //Assert.IsInstanceOfType<LeaderboardV2UpdatePayload> (instance, "variable 'instance' is a LeaderboardV2UpdatePayload");
        }


        /// <summary>
        /// Test the property 'webhook_type'
        /// </summary>
        [Test]
        public void webhook_typeTest()
        {
            // TODO unit test for the property 'webhook_type'
        }
        /// <summary>
        /// Test the property 'leaderboard_data'
        /// </summary>
        [Test]
        public void leaderboard_dataTest()
        {
            // TODO unit test for the property 'leaderboard_data'
        }
        /// <summary>
        /// Test the property 'member_data'
        /// </summary>
        [Test]
        public void member_dataTest()
        {
            // TODO unit test for the property 'member_data'
        }
        /// <summary>
        /// Test the property 'old_leaderboard_ranking'
        /// </summary>
        [Test]
        public void old_leaderboard_rankingTest()
        {
            // TODO unit test for the property 'old_leaderboard_ranking'
        }
        /// <summary>
        /// Test the property 'new_leaderboard_ranking'
        /// </summary>
        [Test]
        public void new_leaderboard_rankingTest()
        {
            // TODO unit test for the property 'new_leaderboard_ranking'
        }

    }

}
