/* 
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SCILL.Api;
using SCILL.Model;
using SCILL.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SCILL.Test
{
    /// <summary>
    ///  Class for testing OneOfbody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OneOfbodyTests
    {
        // TODO uncomment below to declare an instance variable for OneOfbody
        //private OneOfbody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OneOfbody
            //instance = new OneOfbody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OneOfbody
        /// </summary>
        [Test]
        public void OneOfbodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OneOfbody
            //Assert.IsInstanceOfType<OneOfbody> (instance, "variable 'instance' is a OneOfbody");
        }



    }

}
