/* 
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SCILL.Api;
using SCILL.Model;
using SCILL.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SCILL.Test
{
    /// <summary>
    ///  Class for testing TeamEventPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TeamEventPayloadTests
    {
        // TODO uncomment below to declare an instance variable for TeamEventPayload
        //private TeamEventPayload instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TeamEventPayload
            //instance = new TeamEventPayload();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TeamEventPayload
        /// </summary>
        [Test]
        public void TeamEventPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TeamEventPayload
            //Assert.IsInstanceOfType<TeamEventPayload> (instance, "variable 'instance' is a TeamEventPayload");
        }


        /// <summary>
        /// Test the property 'user_id'
        /// </summary>
        [Test]
        public void user_idTest()
        {
            // TODO unit test for the property 'user_id'
        }
        /// <summary>
        /// Test the property 'team_id'
        /// </summary>
        [Test]
        public void team_idTest()
        {
            // TODO unit test for the property 'team_id'
        }
        /// <summary>
        /// Test the property 'session_id'
        /// </summary>
        [Test]
        public void session_idTest()
        {
            // TODO unit test for the property 'session_id'
        }
        /// <summary>
        /// Test the property 'event_name'
        /// </summary>
        [Test]
        public void event_nameTest()
        {
            // TODO unit test for the property 'event_name'
        }
        /// <summary>
        /// Test the property 'event_type'
        /// </summary>
        [Test]
        public void event_typeTest()
        {
            // TODO unit test for the property 'event_type'
        }
        /// <summary>
        /// Test the property 'meta_data'
        /// </summary>
        [Test]
        public void meta_dataTest()
        {
            // TODO unit test for the property 'meta_data'
        }

    }

}
