/* 
 * SCILL API
 *
 * SCILL gives you the tools to activate, retain and grow your user base in your app or game by bringing you features well known in the gaming industry: Gamification. We take care of the services and technology involved so you can focus on your game and content.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@scillgame.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using SCILL.Client;
using SCILL.Api;
using SCILL.Model;

namespace SCILL.Test
{
    /// <summary>
    ///  Class for testing BattlePassesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class BattlePassesApiTests
    {
        private BattlePassesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new BattlePassesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BattlePassesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' BattlePassesApi
            //Assert.IsInstanceOfType(typeof(BattlePassesApi), instance, "instance is a BattlePassesApi");
        }

        /// <summary>
        /// Test ClaimBattlePassLevelReward
        /// </summary>
        [Test]
        public void ClaimBattlePassLevelRewardTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BattlePassLevelId body = null;
            //string appId = null;
            //string bpid = null;
            //var response = instance.ClaimBattlePassLevelReward(body, appId, bpid);
            //Assert.IsInstanceOf<ActionResponse> (response, "response is ActionResponse");
        }
        /// <summary>
        /// Test GetBattlePass
        /// </summary>
        [Test]
        public void GetBattlePassTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string appId = null;
            //string bpid = null;
            //var response = instance.GetBattlePass(appId, bpid);
            //Assert.IsInstanceOf<BattlePass> (response, "response is BattlePass");
        }
        /// <summary>
        /// Test GetBattlePasses
        /// </summary>
        [Test]
        public void GetBattlePassesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string appId = null;
            //var response = instance.GetBattlePasses(appId);
            //Assert.IsInstanceOf<List<BattlePass>> (response, "response is List<BattlePass>");
        }
        /// <summary>
        /// Test UnlockBattlePassLevel
        /// </summary>
        [Test]
        public void UnlockBattlePassLevelTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BattlePassLevelId body = null;
            //string appId = null;
            //string bpid = null;
            //var response = instance.UnlockBattlePassLevel(body, appId, bpid);
            //Assert.IsInstanceOf<ActionResponse> (response, "response is ActionResponse");
        }
    }

}
